Add capabilities in batch client get enrichment activities to use Enrichment flags
GetStream/stream-java pull request #126
Opened 2023-07-11 10:07 UTC by adinovri

2023-07-11 10:16 UTC, xernobyl approved these changes
LGTM

2023-07-12 03:14 UTC, adinovri commented
Hi @xernobyl @JcMinarro when will this changes can be release in new version? Thanks.

2023-07-12 07:35 UTC, xernobyl commented
> Hi @xernobyl @JcMinarro when will this changes can be release in new version? Thanks.

I'll try to have it done in the next 8 hours.

2023-07-12 08:26 UTC, JcMinarro requested changes
The commit message history doesn't follow the expected structure.
On this repository we are using [CommitLint](https://commitlint.js.org/) to check the commit message.

2023-07-12 08:26 UTC, JcMinarro commented on .github/workflows/ci.yml
> +      #  uses: wagoid/commitlint-github-action@v4
Why is it commented on?

2023-07-12 08:26 UTC, JcMinarro commented on build.gradle
> +version = '3.7.0'
Version shouldn't be manual update.
There is a CI job for that

2023-07-12 08:28 UTC, JcMinarro commented
> Hi @xernobyl @JcMinarro when will this changes can be release in new version? Thanks.

We need this PR pass the CI checks, could you fix them?

2023-07-12 08:37 UTC, adinovri commented
Hi @JcMinarro @xernobyl please review here https://github.com/GetStream/stream-java/pull/127, I will close this PR. Thanks.

2023-07-12 08:37 UTC, closed without merging